### ISSUE TITLE
Error while encrypting large files

### ISSUE THREAD

**Issue by IgorCova** [stulzq/DotnetCore.RSA#1]
Exception message: `Interop.Crypto.OpenSslCryptographicException: 'error:0406D06E:rsa routines:RSA_padding_add_PKCS1_type_2:data too large for key size'`

**Comment by stulzq** [comment]
If you are a OSX system, please check whether OpenSSL is installed and If you want to encrypt long strings, you need to split them yourself for segmentation encryption.

**Comment by IgorCova** [comment]
I have Windows 10. Application on the .net core for Linux. Open SSL on the computer isn't specifically set.

So you propose to break a long line into many small ones and encrypt them separately and glue them together?

**Comment by stulzq** [comment]
Yes

**Comment by IgorCova** [comment]
Maybe you know, OpenSSL have another method for encryption large text - and there it (break a long line into many small ones) do it automatically?

**Comment by stulzq** [comment]
RSA algorithm cannot encrypt large text, this is the limitation of the algorithm itself.You said that openssl comes with this way I have not used, but I know that you can split the big text yourself for encryption.

**Comment by stulzq** [comment]
https://github.com/stulzq/RSAUtil This tool may help you

**Comment by IgorCova** [comment]
there is same code for encryption

 ```
public string Encrypt(string data, RSAEncryptionPadding padding)
{
  if (PublicRsa == null)
  {
    throw new ArgumentException("public key can not null");
  }
  byte[] dataBytes = DataEncoding.GetBytes(data);
  var resBytes = PublicRsa.Encrypt(dataBytes, padding);
  return Convert.ToBase64String(resBytes);
}
```
