### ISSUE TITLE
private key 加密,public key 解密时报错

### ISSUE THREAD

**Issue by lzpong** [stulzq/DotnetCore.RSA#4]
private key 加密,public key 解密时报这个错

Internal.Cryptography.CryptoThrowHelper.WindowsCryptographicException:“该项不存在"

这个是咋回事?

public key 加密, private key 解密 倒是正常.

**Comment by stulzq** [comment]
这个问题 我有一篇博客详细介绍过原因 ，关于 RSA 推荐我最新封装的库 https://github.com/stulzq/RSAExtensions
